### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by rgetz** [raas/mbw#16]
in the spec file it says : `License: LGPLv2.1` - which obviously isn't right, since it's not a library.

https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
`A "library" means a collection of software functions and/or data prepared so as to be conveniently linked with application programs (which use some of those functions and data) to form executables.`

mbw is an executable (application program).

Thanks
-Robin

**Comment by raas** [comment]
Huh, you have a point. Thanks for pointing this out.

**Comment by raas** [comment]
Closed with https://github.com/raas/mbw/pull/17.
